name: Pester
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install Pester v5(.1)
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module Pester -AllowPreRelease -Force
    - name: Write Config
      shell: pwsh
      run: |
        $file = '
        $script:ipaddress = "$env:IPADDRESS"
        $script:port = $env:PORT_V62
        $script:login = "$env:LOGIN"
        $script:password = "$env:PASSWORD"
        $script:httponly = [bool]$env:HTTPONLY
        '
        $file | Out-File -FilePath Tests/credential.ps1
        more Tests/credential.ps1
      env:
        IPADDRESS: ${{secrets.IPADDRESS}}
        PORT_V62: ${{secrets.PORT_V62}}
        LOGIN: ${{secrets.LOGIN}}
        PASSWORD: ${{secrets.PASSWORD}}
        HTTPONLY: ${{secrets.HTTPONLY}}
    - name: Pester
      shell: pwsh
      run: |
        Import-Module ./PowerFGT
        cd Tests/integration
        Invoke-Pester * -Output Detailed -CI
      env:
        IPADDRESS: ${{secrets.IPADDRESS}}
        PORT: ${{secrets.PORT_V62}}
        LOGIN: ${{secrets.LOGIN}}
        PASSWORD: ${{secrets.PASSWORD}}
        HTTPONLY: ${{secrets.HTTPONLY}}